[package]
name = "polytype"
version = "6.1.1"
authors = ["Lucas Morales <lucas@lucasem.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/lucasem/polytype-rs"
homepage = "https://github.com/lucasem/polytype-rs"
documentation = "https://docs.rs/polytype"
description = "A Hindley-Milner polymorphic typing system."
keywords = ["typing", "language", "type", "inference", "unification"]
categories = ["science", "data-structures", "algorithms"]
edition = "2018"

[dependencies]
indexmap = "1.0"
itertools = "0.8"
nom = "=4.1.1"
smallvec = "1.4"
typed-arena = "2.0"
